image: rocker/tidyverse

stages:
  - build
  - deploy

building:
  stage: build
  script:
    - R -e "remotes::install_deps(dependencies = T)"
    - R -e 'devtools::check()'

pages:
    stage: deploy
    script:
      - R -e 'devtools::install()'
      - R -e 'pkgdown::build_site()'
      - mkdir public
      - mv docs/* public
    artifacts:
        paths:
            - public
    only:
        - master
        - gitlab-pages
